name: Sync liferay-portal fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" 

jobs:
  sync_liferay_portal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: github-actions

      - name: Checkout jorgediaz-lr/liferay-portal
        uses: actions/checkout@v3
        with:
          repository: 'jorgediaz-lr/liferay-portal'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: liferay-portal

      - name: Sync and find changes
        run: |
          cd liferay-portal
          SHA=$(git rev-parse HEAD)
          gh repo sync jorgediaz-lr/liferay-portal --source liferay/liferay-portal --branch master
          git pull origin master
          ../github-actions/scripts/changes.sh "$SHA" > changes.txt
          if grep -q "Changes" changes.txt; then
            gh issue create --title "Changes" --body "$(cat changes.txt)" --repo liferay-database-infra/liferay-portal
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT }}
